# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: aws-waf
  description: This component is responsible for provisioning an AWS Web Application Firewall (WAF) with an associated managed rule group
  homepage: https://cloudposse.com/accelerate
  topics: terraform, terraform-component





